

version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:15
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  server:
    container_name: server
    build: ./server
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./server:/cereal/server
    depends_on:
      - db
  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/cereal/client
    command: "yarn dev"
    depends_on:
      - backend
  yaichi:
    container_name: yaichi
    image: mtsmfm/yaichi:1.5.0
    ports:
      - 80:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock